version: "3"
services:
  # Для запуска приложения запустите: docker-compose up web
  web:
    image: nginx:1.17-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/config/nginx.conf
      - ./:/code
    command: nginx -c /config/nginx.conf
    user: root
    ports:
      - "8080:8080"
    depends_on:
      - fpm
      - db
    stop_signal: SIGTERM

  # Процесс fpm
  fpm:
    build: ./docker/php
    volumes:
      - ./:/code


  # Для запуска тестов запустите: docker-compose up tests
  tests:
    build: ./docker/php
    command: /usr/local/bin/codecept run -vvv
    volumes:
      - ./:/code
    depends_on:
      - web

  # Для запуска терминала с настроенной средой php запустите: docker-compose run terminal
  terminal:
    build: ./docker/php
    entrypoint: /bin/sh
    volumes:
      - ./:/code

  # MySQL
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lumen_push
      MYSQL_ROOT_PASSWORD: yd9Maw
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

# Тома
volumes:
  dbdata:
    driver: local